
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Booksmart.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ShortStory
{

    public int ShortStoryID { get; set; }

    public string ShortStoryDescription { get; set; }

    public string ShortStoryPdfPath { get; set; }

    public string Image { get; set; }

}

}
