//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booksmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheoryGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TheoryGame()
        {
            this.TheoryGameAttempts = new HashSet<TheoryGameAttempt>();
            this.TheoryGameQuestions = new HashSet<TheoryGameQuestion>();
        }
    
        public int TheoryGameID { get; set; }
        public string Description { get; set; }
        public string TheoryVideo { get; set; }
        public decimal TheoryType { get; set; }
        public int LevelID { get; set; }
    
        public virtual Level Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheoryGameAttempt> TheoryGameAttempts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheoryGameQuestion> TheoryGameQuestions { get; set; }
    }
}
