
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Booksmart.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TheoryGameQuestion
{

    public int TheoryGameID { get; set; }

    public int ID { get; set; }

    public int TheoryQuestionID { get; set; }



    public virtual TheoryGame TheoryGame { get; set; }

    public virtual TheoryQuestion TheoryQuestion { get; set; }

}

}
